version: "3"
services:
  rlhf:
    image: rlhf:latest
    volumes:
      - ./:/rlhf
    build:
      context: .
      dockerfile: docker/Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1', '2', '3', '4', '5', '6', '7']
              # device_ids: ['1']
              capabilities: [gpu]
    tty: true
    shm_size: '128gb'
    ulimits:
      memlock: -1
    network_mode: "host"